
services:
  shoegame:
    container_name: shoegamev2_app
    image: eugenekwaka/shoegame:v2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - shoegamev2-network
    restart: unless-stopped

  postgres:
    container_name: shoegamev2_DB
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - shoegamev2_DB:/data/postgres
    ports:
      - "5433:5432"  # Host:Container — avoids conflict with dev postgres
    networks:
      - shoegamev2-network
    restart: unless-stopped

  pgadmin:
    container_name: shoegamev2_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - shoegamev2_pgadmin:/var/lib/pgadmin
    ports:
      - "5100:80"  # Host:Container — avoids conflict with dev pgAdmin
    networks:
      - shoegamev2-network
    restart: unless-stopped

networks:
  shoegamev2-network:
    driver: bridge

volumes:
  shoegamev2_DB:
  shoegamev2_pgadmin:
